<?php

namespace PlusTimeIT\EasyForms\Traits;

trait FieldTrait
{
    use Attributes\HasActive;
    use Attributes\HasAppendIcon;
    use Attributes\HasAppendInnerIcon;
    use Attributes\HasAutoFocus;
    use Attributes\HasBaseColor;
    use Attributes\HasBgColor;
    use Attributes\HasCenterAffix;
    use Attributes\HasClearable;
    use Attributes\HasColor;
    use Attributes\HasCols;
    use Attributes\HasComponent;
    use Attributes\HasDensity;
    use Attributes\HasDependsOn;
    use Attributes\HasDisabled;
    use Attributes\HasDiscriminator;
    use Attributes\HasEager;
    use Attributes\HasError;
    use Attributes\HasErrorMessages;
    use Attributes\HasFlat;
    use Attributes\HasFocused;
    use Attributes\HasHelp;
    use Attributes\HasHideDetails;
    use Attributes\HasHint;
    use Attributes\HasIcons;
    use Attributes\HasId;
    use Attributes\HasLabel;
    use Attributes\HasMaxErrors;
    use Attributes\HasMaxRows;
    use Attributes\HasMessages;
    use Attributes\HasName;
    use Attributes\HasOffset;
    use Attributes\HasOrder;
    use Attributes\HasOutlined;
    use Attributes\HasPersistance;
    use Attributes\HasPlaceholder;
    use Attributes\HasPrefix;
    use Attributes\HasPrependIcon;
    use Attributes\HasPrependInnerIcon;
    use Attributes\HasReadOnly;
    use Attributes\HasRequireConfirmation;
    use Attributes\HasRequired;
    use Attributes\HasRole;
    use Attributes\HasRounded;
    use Attributes\HasRules;
    use Attributes\HasShowIf;
    use Attributes\HasSingleLine;
    use Attributes\HasSuffix;
    use Attributes\HasTheme;
    use Attributes\HasTooltip;
    use Attributes\HasType;
    use Attributes\HasValidationOn;
    use Attributes\HasValue;
    use Attributes\HasVariant;
    use Creatable;
    use Transformable;
}
